collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8387097
  brandStrength: 0.1382774200756103
  lightness: 0.4802867
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  rhythmicContrast: 1
typography_spectrum: 0.3333333
layout_spectrum: 0.1127138726878911
name: Airfare Hack
