collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.6272401
color:
  saturation: 0.1513541729655117
  brandStrength: 0.1382774200756103
  rhythmicContrast: 0.9182996582239866
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.1563650767784566
layout_spectrum: 0.1127138726878911
name: Airfare Hack
